In [1]:
import numpy as np
np.random.seed(1)

from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten, Input
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder


Using TensorFlow backend.
/usr/local/src/conda3_runtime/home/envs/DSX-Python35-Spark/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# define documents
docs = ['king is man',
'a king marrys queen',
'a queen marrys king',
'some unrelated workds'
'queen is woman']
docs

['king is man',
 'a king marrys queen',
 'a queen marrys king',
 'some unrelated workdsqueen is woman']

In [3]:
vocab_size = 50

In [4]:
oh = np.array(one_hot('king queen man woman unrelated', vocab_size)).reshape(-1,1)
oh

array([[14],
       [ 6],
       [ 1],
       [ 7],
       [12]])

In [13]:
enc = OneHotEncoder()
enc.fit(np.array(range(vocab_size)).reshape(-1,1))
oh_enc = enc.transform(oh).toarray()
oh_enc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 

In [14]:
encoded_docs = [one_hot(d, vocab_size) for d in docs]
encoded_docs 

[[14, 1, 1], [39, 14, 19, 6], [39, 6, 19, 14], [9, 12, 11, 1, 7]]

In [15]:
max_length = 24
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_docs 

array([[14,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [39, 14, 19,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [39,  6, 19, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 9, 12, 11,  1,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [16]:
tuples = np.empty((0, 2))
for padded_doc in padded_docs:
    length = len(padded_doc)
    for i in range(length):
        if padded_doc[i] != 0:
            if i<length-1 & padded_doc[i+1] != 0:
                tuples = np.append(tuples, [[padded_doc[i],padded_doc[i+1]]], axis=0) 
                if i<length-2 & padded_doc[i+2] != 0:
                    tuples = np.append(tuples, [[padded_doc[i],padded_doc[i+2]]], axis=0) 
            if i > 0:
                tuples = np.append(tuples, [[padded_doc[i],padded_doc[i-1]]], axis=0) 
                if i > 1:
                    tuples = np.append(tuples, [[padded_doc[i],padded_doc[i-2]]], axis=0) 

    
print (tuples.shape)
tuples



(35, 2)


array([[14.,  1.],
       [ 1., 14.],
       [ 1.,  1.],
       [ 1., 14.],
       [39., 14.],
       [39., 19.],
       [14., 19.],
       [14.,  6.],
       [14., 39.],
       [19.,  6.],
       [19., 14.],
       [19., 39.],
       [ 6., 19.],
       [ 6., 14.],
       [39.,  6.],
       [39., 19.],
       [ 6., 19.],
       [ 6., 14.],
       [ 6., 39.],
       [19., 14.],
       [19.,  6.],
       [19., 39.],
       [14., 19.],
       [14.,  6.],
       [ 9., 12.],
       [ 9., 11.],
       [12., 11.],
       [12.,  9.],
       [11., 12.],
       [11.,  9.],
       [ 1.,  7.],
       [ 1., 11.],
       [ 1., 12.],
       [ 7.,  1.],
       [ 7., 11.]])

In [17]:
onehotlabels_x = enc.transform(tuples[:,0].reshape(-1, 1)).toarray()

print  (onehotlabels_x.shape)
print ('---')
print (onehotlabels_x)
print ('---')
print (onehotlabels_x[0])

(35, 50)
---
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [19]:
onehotlabels_y = enc.transform(tuples[:,1].reshape(-1, 1)).toarray()

print  (onehotlabels_y.shape)
print ('---')
print (onehotlabels_y)
print ('---')
print (onehotlabels_y[0])

(35, 50)
---
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [20]:
model = Sequential()

input = Dense(50, input_shape=(50,), activation='relu')
model.add(input)
bottleneck = Dense(2, activation='relu')
model.add(bottleneck)
model.add(Dense(50, activation='softmax'))
# compile the model
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

# fit the model
model.fit(onehotlabels_x, onehotlabels_y, epochs=500, verbose=1)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 102       
_________________________________________________________________
dense_3 (Dense)              (None, 50)                150       
Total params: 2,802
Trainable params: 2,802
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/500
35/35 [==============================] - 0s - loss: 0.0980 - acc: 0.9800     
Epoch 2/500
35/35 [==============================] - 0s - loss: 0.0979 - acc: 0.9800     
Epoch 3/500
35/35 [==============================] - 0s - loss: 0.0978 - acc: 0.9800     
Epoch 4/500
35/35 [==============================] - 0s - loss: 0.0977 - acc: 0.9800     
Epoch 5/500
35/35 [====================

35/35 [==============================] - 0s - loss: 0.0739 - acc: 0.9800     
Epoch 84/500
35/35 [==============================] - 0s - loss: 0.0733 - acc: 0.9800     
Epoch 85/500
35/35 [==============================] - 0s - loss: 0.0728 - acc: 0.9800     
Epoch 86/500
35/35 [==============================] - 0s - loss: 0.0723 - acc: 0.9800     
Epoch 87/500
35/35 [==============================] - 0s - loss: 0.0718 - acc: 0.9800     
Epoch 88/500
35/35 [==============================] - 0s - loss: 0.0713 - acc: 0.9800     
Epoch 89/500
35/35 [==============================] - 0s - loss: 0.0708 - acc: 0.9800     
Epoch 90/500
35/35 [==============================] - 0s - loss: 0.0704 - acc: 0.9800     
Epoch 91/500
35/35 [==============================] - 0s - loss: 0.0699 - acc: 0.9800     
Epoch 92/500
35/35 [==============================] - 0s - loss: 0.0696 - acc: 0.9800     
Epoch 93/500
35/35 [==============================] - 0s - loss: 0.0692 - acc: 0.9800     
Epoch 94/500

35/35 [==============================] - 0s - loss: 0.0600 - acc: 0.9800     
Epoch 173/500
35/35 [==============================] - 0s - loss: 0.0600 - acc: 0.9800     
Epoch 174/500
35/35 [==============================] - 0s - loss: 0.0599 - acc: 0.9800     
Epoch 175/500
35/35 [==============================] - 0s - loss: 0.0599 - acc: 0.9800     
Epoch 176/500
35/35 [==============================] - 0s - loss: 0.0598 - acc: 0.9800     
Epoch 177/500
35/35 [==============================] - 0s - loss: 0.0598 - acc: 0.9800     
Epoch 178/500
35/35 [==============================] - 0s - loss: 0.0597 - acc: 0.9800     
Epoch 179/500
35/35 [==============================] - 0s - loss: 0.0597 - acc: 0.9800     
Epoch 180/500
35/35 [==============================] - 0s - loss: 0.0596 - acc: 0.9800     
Epoch 181/500
35/35 [==============================] - 0s - loss: 0.0596 - acc: 0.9800     
Epoch 182/500
35/35 [==============================] - 0s - loss: 0.0595 - acc: 0.9800     
Ep

35/35 [==============================] - 0s - loss: 0.0568 - acc: 0.9800     
Epoch 262/500
35/35 [==============================] - 0s - loss: 0.0568 - acc: 0.9800     
Epoch 263/500
35/35 [==============================] - 0s - loss: 0.0568 - acc: 0.9800     
Epoch 264/500
35/35 [==============================] - 0s - loss: 0.0567 - acc: 0.9800     
Epoch 265/500
35/35 [==============================] - 0s - loss: 0.0567 - acc: 0.9800     
Epoch 266/500
35/35 [==============================] - 0s - loss: 0.0567 - acc: 0.9800     
Epoch 267/500
35/35 [==============================] - 0s - loss: 0.0567 - acc: 0.9800     
Epoch 268/500
35/35 [==============================] - 0s - loss: 0.0567 - acc: 0.9800     
Epoch 269/500
35/35 [==============================] - 0s - loss: 0.0566 - acc: 0.9800     
Epoch 270/500
35/35 [==============================] - 0s - loss: 0.0566 - acc: 0.9800     
Epoch 271/500
35/35 [==============================] - 0s - loss: 0.0566 - acc: 0.9800     
Ep

35/35 [==============================] - 0s - loss: 0.0549 - acc: 0.9800     
Epoch 351/500
35/35 [==============================] - 0s - loss: 0.0549 - acc: 0.9800     
Epoch 352/500
35/35 [==============================] - 0s - loss: 0.0549 - acc: 0.9800     
Epoch 353/500
35/35 [==============================] - 0s - loss: 0.0548 - acc: 0.9800     
Epoch 354/500
35/35 [==============================] - 0s - loss: 0.0548 - acc: 0.9800     
Epoch 355/500
35/35 [==============================] - 0s - loss: 0.0548 - acc: 0.9800     
Epoch 356/500
35/35 [==============================] - 0s - loss: 0.0548 - acc: 0.9800     
Epoch 357/500
35/35 [==============================] - 0s - loss: 0.0548 - acc: 0.9800     
Epoch 358/500
35/35 [==============================] - 0s - loss: 0.0547 - acc: 0.9800     
Epoch 359/500
35/35 [==============================] - 0s - loss: 0.0547 - acc: 0.9800     
Epoch 360/500
35/35 [==============================] - 0s - loss: 0.0547 - acc: 0.9800     
Ep

35/35 [==============================] - 0s - loss: 0.0533 - acc: 0.9800     
Epoch 440/500
35/35 [==============================] - 0s - loss: 0.0533 - acc: 0.9800     
Epoch 441/500
35/35 [==============================] - 0s - loss: 0.0532 - acc: 0.9800     
Epoch 442/500
35/35 [==============================] - 0s - loss: 0.0532 - acc: 0.9800     
Epoch 443/500
35/35 [==============================] - 0s - loss: 0.0532 - acc: 0.9800     
Epoch 444/500
35/35 [==============================] - 0s - loss: 0.0532 - acc: 0.9800     
Epoch 445/500
35/35 [==============================] - 0s - loss: 0.0532 - acc: 0.9800     
Epoch 446/500
35/35 [==============================] - 0s - loss: 0.0532 - acc: 0.9800     
Epoch 447/500
35/35 [==============================] - 0s - loss: 0.0531 - acc: 0.9800     
Epoch 448/500
35/35 [==============================] - 0s - loss: 0.0531 - acc: 0.9800     
Epoch 449/500
35/35 [==============================] - 0s - loss: 0.0531 - acc: 0.9800     
Ep

In [22]:
model = Sequential()
model.add(input)
model.add(bottleneck)
model.compile(optimizer=Adam(lr=0.001), loss='binary_crossentropy', metrics=['acc'])
test = model.predict(oh_enc)
print (test)


[[7.190031   4.8633647 ]
 [7.918069   8.700294  ]
 [0.         6.2088766 ]
 [0.         6.0469513 ]
 [0.23022771 3.9706519 ]]


In [23]:
#Keras Supports all this in one layer called Embedding
model = Sequential()
model.add(Embedding(1000, 2, input_length=5))
model.compile('rmsprop', 'mse')

input_array = np.random.randint(1000, size=(12, 5)) # 12 documents, 5 words per document
input_array


array([[935,  61, 707,  77,  12],
       [160, 331, 883, 696, 503],
       [569, 920, 724, 206, 349],
       [564, 205, 822, 429, 111],
       [462, 939, 240, 131, 557],
       [  3, 985, 645, 448, 419],
       [ 30, 275, 492,  52, 941],
       [885, 844, 469,  98, 124],
       [952,  29, 351,  48, 545],
       [889, 858, 100, 358, 816],
       [586, 389, 583, 681, 116],
       [ 35, 677, 897, 501, 503]])

In [24]:

output_array = model.predict(input_array)
print (output_array.shape)
print (output_array)

(12, 5, 2)
[[[-4.12422791e-02  2.16267966e-02]
  [-3.42080221e-02  1.00561865e-02]
  [-3.81315462e-02 -1.92495231e-02]
  [ 1.60436518e-02 -4.08720262e-02]
  [ 2.05826759e-03 -4.44509834e-03]]

 [[-4.96067405e-02  1.60832889e-02]
  [-2.08471175e-02  2.31127031e-02]
  [ 3.68520506e-02  1.16566643e-02]
  [-1.34305470e-02 -4.11561951e-02]
  [ 1.02813728e-02 -2.91618351e-02]]

 [[-2.16879696e-03 -1.75670497e-02]
  [-1.24173164e-02 -1.08409300e-02]
  [-2.09879875e-02  4.49026264e-02]
  [ 1.62095465e-02 -5.66877052e-03]
  [ 4.85831015e-02 -2.82569770e-02]]

 [[ 3.99027020e-03  2.82685831e-03]
  [ 2.89091207e-02  3.30701582e-02]
  [-4.07975912e-03 -2.14658976e-02]
  [-4.52235937e-02 -3.76255624e-02]
  [ 1.22299045e-03 -4.32404168e-02]]

 [[-2.19511874e-02 -2.80746110e-02]
  [-1.36595368e-02  1.71805061e-02]
  [-4.63915244e-02 -1.47732124e-02]
  [-7.76762888e-03  3.20998542e-02]
  [ 4.45470214e-05  1.38112418e-02]]

 [[-2.49672681e-04 -1.28221400e-02]
  [-2.37118360e-02  1.76751874e-02]
  [ 1.3

In [25]:
# define documents
docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Really Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [26]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[4, 4], [48, 43], [26, 42], [36, 43], [47], [10, 6], [8, 42], [19, 48], [8, 43], [49, 30, 4, 49]]


In [27]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[ 4  4  0  0]
 [48 43  0  0]
 [26 42  0  0]
 [36 43  0  0]
 [47  0  0  0]
 [10  6  0  0]
 [ 8 42  0  0]
 [19 48  0  0]
 [ 8 43  0  0]
 [49 30  4 49]]


In [28]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [30]:
import numpy as np
np.hstack((model.predict(padded_docs),np.array(labels).reshape(10,1)))

array([[0.5356909 , 1.        ],
       [0.54151392, 1.        ],
       [0.52594894, 1.        ],
       [0.55283898, 1.        ],
       [0.54503894, 1.        ],
       [0.45687893, 0.        ],
       [0.47465068, 0.        ],
       [0.46119082, 0.        ],
       [0.49743998, 0.        ],
       [0.42303309, 0.        ]])